blank_issues_enabled: false
contact_links:
  - name: Hacking Escape Room Webseite
    url: https://hackingescaperoom.252425.xyz
    about: Informationen zum Hacking Escape Room und Einstieg in die Rätsel.
